# Store the multiplication table generated by user in problem3 in table.txt
user_no = int(input("Enter the number: "))
table = [user_no*i for i in range(1,11)]
print(table)
str(table)

with open("CH12_PS//table.txt", "a") as f:
    f.write(str(table) + "\n")